buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        maven { url = 'https://cursemaven.com' }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:3.+'
    }
}
        
apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'eclipse'
apply plugin: 'maven-publish'

repositories {
    maven { url = 'https://cursemaven.com' }
    maven { url = 'https://maven.cleanroommc.com' }
    maven { url = 'https://repo.spongepowered.org/maven' }
    maven { url = 'https://maven.tterrag.com/' }
    flatDir {
        dirs 'libs'
    }
}

version = '1.0'
group = 'com.flux_applied'
archivesBaseName = 'flux_applied'

sourceCompatibility = targetCompatibility = compileJava.sourceCompatibility = compileJava.targetCompatibility = '1.8'

sourceSets {
    api
}

sourceSets.main.compileClasspath += sourceSets.api.output
sourceSets.main.runtimeClasspath += sourceSets.api.output

minecraft {
    mappings channel: 'snapshot', version: '20171003-1.12'

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
        }

        server {
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
        }
    }
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2859'

    compile fg.deobf("curse.maven:ae2-extended-life-570458:6302098")
    compile fg.deobf("curse.maven:ae2fluidcraft-rework-unofficial-1404390:7742544")
    
    implementation files('libs/terminal_interaction_integration-1.0.jar')
    
    compileOnly fg.deobf("curse.maven:the-one-probe-community-edition-885670:7718301")
}

jar {
    manifest {
        attributes([
            "Specification-Title": "flux_applied",
            "Specification-Vendor": "flux_applied",
            "Specification-Version": "1",
            "Implementation-Title": project.name,
            "Implementation-Version": "${version}",
            "Implementation-Vendor" :"flux_applied",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

jar.finalizedBy('reobfJar') 

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file:///${project.projectDir}/mcmodsrepo"
        }
    }
}
